### ISSUE TITLE
issues updating Drupal

### ISSUE THREAD

**Issue by manarak** [WebKings-ca/gocomposer#1]
Hello, 
I have just installed a fresh development site using a theme that was provided with codebase and database file.
The site works fine.
The version of the installed Drupal is 8.6.5 which I want to upgrade to the latest version (currently 8.6.8).

I follow the instructions in the readme:
> cd path/to/drupal/project/repo
> composer require webkings-ca/gocomposer:dev-master
> composer gocomposer

I got an error message saying it can't find the database credentials inspite finding the settings.php file

then it asks me to discard changes? no idea what this is about, I answered yes to everything.
it processes lots of stuff and then says it was successful.

When visiting /web I get to the drupal install procedure for Drupal version 8.6.8 ???
I guess this is due to the script not recognizing database credentials?

What should I do?

**Comment by manarak** [comment]
here are some errors from my SSH log:
`Please select which Settings.php file you want to use for your Environment (Recommended Version is: [0])
  [0] /*****/sites/default/settings.php

 > 0
You have just selected: /*****/sites/default/settings.php
                                                                                                                    [39;49m
[WARNING] Saving Environment from settings.php directly didnt succeed. Reason : Error: Unable to find Databases        [39;49m
          Credentials. Aborting.. 
          
Generating autoload files
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Class 'Drupal\Core\Session\AccountInterface' not found in /*****/core/includes/bootstrap.inc, line 83 
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Class 'Drupal\Core\Session\AccountInterface' not found in /*****/core/includes/bootstrap.inc, line 83 
tar: .: file changed as we read it

Fatal error: Class 'Drupal\Core\Session\AccountInterface' not found in /*****/core/includes/bootstrap.inc on line 83

In Settings.php line 149:
                                                   
  Missing $settings['hash_salt'] in settings.php.   


In BootstrapHook.php line 32:
                                                                      
  Bootstrap failed. Run your command with -vvv for more information.  
                                                                      `

**Comment by WebKings-ca** [comment]
Hi @manarak , 

Thanks for your  interest in this plug-in.. 

If you can provide me with the following information I might be able to suggest a possible solution:

1) How did you install you Drupal 8 core files initially?

2) Can you post your initial settings.php file (Please use the code tags so it's clear to see)

3) If your Drupal Root has a composer.json file, Please post it..

4) Is your current local environment properly set-up? for this plug-in to work your CLI (Command Line Interface) should have a proper setup for Apache, MySql and PHP (Preferably 7 and above).

Please note also, as mentioned in the Instructions page, that this plug-in will convert your site to the template found [here](https://github.com/drupal-composer/drupal-project)

**Comment by manarak** [comment]
Hello Ahmad

 

Thank you for writing software for Drupal – much appreciated.

 

To answer your questions: 

1-      Initial install of Drupal was from a Theme I acquired. A fully loaded demo repo + sql file.

2-      The settings file was pretty standard. See attached.

3-      The composer.json file is attached to this email as well

4-      I have no idea if the environment is properly settup. I host at « Metanet » which is a major host here in Switzerland. They usually do a good job. The control panel is plesk. Composer is installed and working, latest version. But I know the available shell commands are very limited. 

Here is a list :



basename, cat, cd, cp, date, echo, env, expr, file, less, ln ,ls

mkdir, more, mv, pwd, readlink, rm, sed, sort, tail, touch, tput

tr, uname, uniq, xargs, wc, which, chmod, printenv, awk, gawk,

cut, sleep, chown, chgrp

curl, rsync, scp, ssh, ssh-keygen, ssh-keyscan, wget

vi, vim, nano

gunzip, gzip, tar, unzip, zip, bunzip2, bzip2

find, grep, diff

mysql, mysqldump

composer, drush, git, patch, wp (WP-CLI)

 

PHP 5.6: /usr/bin/php bzw. php

PHP 7.0: /opt/php70/bin/php

PHP 7.1: /opt/php71/bin/php

PHP 7.2: /opt/php72/bin/php

PHP 7.3: /opt/php73/bin/php

 

 

I was lucky enough to find a simple way to upgrade drupal :

1- in my original composer.json, I delete the "replace" section and add this line at the beginning of the require section:
"drupal/core": "^8.6.8",

2- I delete the /vendor directory

3- from my drupal root directory, I run:
composer update drupal/core --with-dependenci

This is so simple and works (for the moment).

 

Best Regards

Manarak

 

 

Von: Ahmad Khalil [mailto:notifications@github.com] 
Gesendet: Freitag, 8. Februar 2019 23:21
An: WebKings-ca/gocomposer
Cc: manarak; Mention
Betreff: Re: [WebKings-ca/gocomposer] issues updating Drupal (#1)

 

Hi @manarak <https://github.com/manarak>  ,

Thanks for your interest in this plug-in..

If you can provide me with the following information I might be able to suggest a possible solution:

1.      How did you install you Drupal 8 core files initially?

2.      Can you post your initial settings.php file (Please use the code tags so it's clear to see)

3.      If your Drupal Root has a composer.json file, Please post it..

4.      Is your current local environment properly set-up? for this plug-in to work your CLI (Command Line Interface) should have a proper setup for Apache, MySql and PHP (Preferably 7 and above).

Please note also, as mentioned in the Instructions page, that this plug-in will convert your site to the template found here <https://github.com/drupal-composer/drupal-project>

**Comment by WebKings-ca** [comment]
Hi @manarak,

Happy to know you found a solution to your issue... Just some points I would like to mention to clear things up for other users of this plug-in:

1) This Plug-in main purpose is to convert your existing site into the recommended latest template for Drupal 8 sites which makes your site to be fully composer managed. At the same time it updates Drupal core to the latest version. Once the plug-in is run it's gracefully removed as a dependancy in you new `composer.json` file.

2) If you just need to update Drupal 8 core (and not convert to this **new  composer managed template**), you can view other ways to update [here](https://www.drupal.org/docs/8/update).

3) For new users of this plug-in, you should run it in your **Local** environment.. Not on your production site.

Finally, Your local environment should have a proper CLI (Command Line Interface) setup for Apache, MySql and PHP (Preferably 7 and above).
