### ISSUE TITLE
File not found on Windows

### ISSUE THREAD

**Issue by Bence98007** [WebKings-ca/gocomposer#11]
Hi there!

Wanted to try out gocomposer. I get this error msg:
`Access denied - C:\USERS\USER\DESKTOP\USER\DRUPAL8/SITES
File not found - -NAME

  [ErrorException]
  Undefined offset: 0

gocomposer`

The problem could be that I use windows, and the path (in the program itself) uses '/' not '\' ?

Thanks!

**Comment by WebKings-ca** [comment]
@Bence98007,

Can you inform me of the following:
1) Describe your local environment please (PHP, MySql, composer and Apache)
2) Are you using some type of shell for Windows?
3) Which version of Drupal 8 core are you using?
4) Post the whole log of running the Plugin here in code tags.

Thanks..
