### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Yaml\Yaml::parseFile() in /vendor/webkings-ca/gocomposer/src/Utility/DrupalInspector.php:29

### ISSUE THREAD

**Issue by danielcatao** [WebKings-ca/gocomposer#12]
I'm trying to migrate from Drupal 8.7.10 to 8.8.2.
gocomposer gives fatal error after create composer.json
can't run gocomposer again it gives Exception You current installation is already of type drupal-composer/drupal-project... Aborting...
Running on centos PHP is 7.3.1

**Comment by WebKings-ca** [comment]
Hello @danielcatao,

Can you restore your site to its original state and run the plug-in again and post the full output here in Code tags...

Also, please do tell me if you're using a local environment...
