### ISSUE TITLE
cp: cannot stat ‘/var/www/html/mysite.com/Libraries/.’: No such file or directory

### ISSUE THREAD

**Issue by danielcatao** [WebKings-ca/gocomposer#13]
I'm trying to migrate from Drupal 8.7.10 to 8.8.2.
gocomposer warning after Writing lock file Generating autoload files and before Scaffolding files for drupal/core
Running on centos PHP is 7.3.1

**Comment by WebKings-ca** [comment]
@danielcatao ,

Please run the plug-in in your local environment and then copy files and Database to your production server.
