### ISSUE TITLE
Backup completed Error Exception trying to rename settings.tmp.php

### ISSUE THREAD

**Issue by geneatwell** [WebKings-ca/gocomposer#14]
The backup was completed in the default Backup directory and the environment was saved to the .env file, but the directories were not moved to the web subdirectory.
Last message was "[ErrorException]                                                             
  rename(/home/darwus/sadrupal8/settings.tmp.php,/home/darwus/sadrupal8/sites  
  /default/settings.php): Permission denied"
followed by gocomposer and then to the command prompt

**Comment by geneatwell** [comment]
Just set up another site and copied things to it instead of trying this.  Thanks for the effort.

**Comment by WebKings-ca** [comment]
@geneatwell ,
 A possible solution to your issue is to run the following command before running the plug-in:

`chmod -R 755 /home/darwus/sadrupal8`
