### ISSUE TITLE
PHP requirement 

### ISSUE THREAD

**Issue by bg2k** [WebKings-ca/gocomposer#15]
[InvalidArgumentException]
  Package webkings-ca/gocomposer at version dev-master has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

my php is: 7.4

**Comment by WebKings-ca** [comment]
Hi @bg2k,

This is due to the fact the plugin has been tested on `PHP 5.6`. You can give it a shot at your PHP version by changing this line in `composer.json`:

```
    "platform": {
      "php": "5.6"
    }
```

To: 

```
    "platform": {
      "php": "7.4"
    }
```
