### ISSUE TITLE
Installing webkings-ca/gocomposer (dev-master f40c104): Cloning f40c10476a ing failed using an ssh key for authentication

### ISSUE THREAD

**Issue by hellojaison** [WebKings-ca/gocomposer#17]
Hi,

I have trying to install gocomposer via composer. Showing the below error. How can I solve this issue ?

"Installing webkings-ca/gocomposer (dev-master f40c104): Cloning f40c10476a
ing failed using an ssh key for authentication, enter your GitHub credential
 access private repos
 to https://github.com/settings/tokens/new?scopes=repo&description=Composer+
rvwks024+2020-10-11+1613
etrieve a token. It will be stored in "C:/Users/jmathew/AppData/Roaming/Comp
/auth.json" for future use by Composer.
Token (hidden):"

**Comment by WebKings-ca** [comment]
@hellojaison ,

Issue seems with your Github ssh keys, Make sure they're properly configured... Nothing to do with the plugin

**Comment by hellojaison** [comment]
@WebKings-ca ,
Thanks for your support. I will check again
