### ISSUE TITLE
Issue when trying to use gocomposer

### ISSUE THREAD

**Issue by CaughtInTheBrambles** [WebKings-ca/gocomposer#4]
I tried this,
downloaded gocomposer using composer
ran composer gocomposer
followed the on screen prompts and got
./libraries/places-1.10.0/
  [Exception]
  Unable to determine Drupal core version.

gocomposer

docs/source/layouts/documentation.erb
./libraries/places-1.10.0/docs/source/examples.html.md.erb
./libraries/places-1.10.0/docs/Gemfile.lock
./libraries/places-1.10.0/docs/Gemfile
./libraries/places-1.10.0/docs/config.rb
./libraries/places-1.10.0/docs/.gitignore

 [OK] Success: Your Site Files and Database have been backedup to the /backup folder..

My composer.json looks like this
`{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.24",
        "wikimedia/composer-merge-plugin": "^1.4",
        "drupal/webform": "^5.0@beta",
        "drupal/paragraphs": "^1.2",
        "drupal/bootstrap": "^3.6",
        "drupal/bootstrap_paragraphs": "^2.0@beta",
        "drupal/pathauto": "^1.0",
        "drupal/token": "^1.0",
        "drupal/admin_toolbar": "^1.20",
        "drupal/google_analytics": "^2.2",
        "drupal/ds": "^3.1",
        "drupal/honeypot": "^1.27",
        "drupal/cookieconsent": "^1.2",
        "drupal/libraries": "3.x-dev",
        "drupal/views_bootstrap": "^3.0",
        "drupal/config_split": "^1.2",
        "drupal/bootstrap_layouts": "^5.1",
        "drupal/geofield": "^1.0@alpha",
        "drupal/geocoder": "^2.0@alpha",
        "drupal/address": "^1.2",
        "drupal/metatag": "^1.3",
        "drupal/smtp": "^1.0@beta",
        "drupal/backup_migrate": "^4.0@beta",
        "drupal/file_browser": "^1.1",
        "drupal/rules": "^3.0",
        "drupal/core": "~8.6",
        "drupal/eva": "^1.2",
        "drupal/viewsreference": "^1.0",
        "drupal/image_widget_crop": "^2.1",
        "drupal/svg_formatter": "^1.5",
        "drupal/dropzonejs": "^2.0",
        "drupal/video_embed_field": "^2.0",
        "drupal/media_entity_actions": "^1.0",
        "drupal/search_api": "^1.6",
        "drupal/redirect": "^1.0",
        "drupal/inline_entity_form": "^1.0",
        "drupal/media_entity": "^1.7",
        "drupal/media_entity_twitter": "^1.3",
        "drupal/easy_install": "^10.0",
        "drupal/xmlsitemap": "^1.0",
        "drupal/leaflet": "^1.0",
        "drupal/leaflet_more_maps": "^1.0",
        "drupal/geysir": "^1.0",
        "drupal/views_geojson": "1.x-dev",
        "drupal/easy_breadcrumb": "^1.8",
        "drupal/eu_cookie_compliance": "^1.2",
        "webkings-ca/gocomposer": "dev-master",
        "drush/drush": "^9.5"
		
    },

    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        },
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": [
          "Drupal\\Core\\Composer\\Composer::ensureHtaccess"
        ],
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}

Any suggestions or solutions? or indeed further questions.`

**Comment by WebKings-ca** [comment]
Hi @CaughtInTheBrambles (again),

If you can provide me with the following info I might suggest a solution for your issue:

1) How did you initially install Drupal 8 Core?

2) Can you please provide your _original_ `composer.json` file fully in `code tags` please.

3) The Following output you mentioned:

```
./libraries/places-1.10.0/
[Exception]
Unable to determine Drupal core version.

gocomposer

docs/source/layouts/documentation.erb
./libraries/places-1.10.0/docs/source/examples.html.md.erb
./libraries/places-1.10.0/docs/Gemfile.lock
./libraries/places-1.10.0/docs/Gemfile
./libraries/places-1.10.0/docs/config.rb
./libraries/places-1.10.0/docs/.gitignore

[OK] Success: Your Site Files and Database have been backedup to the /backup folder..
```

When in the execution of the Plug-in do you get it? after the prompt to backup your site? I would you rather provide me with the full output (in code tags please) from start to finish..

4) What is your current setup for your Local Environment?
  (a) Are you use MacOS or windows?
  (b) Do you have you CLI (Command Line Interface) set up with Apache, MySql and PHP (version 7 or greater)
  (c) Do you have composer installed globally?

5) In your existing site have you installed custom third party Libraries? and if so which ones?

6) Please provide me a screen shot of all the sub-folders in your `/Libraries` directory..

At first glance it might seem a lot to ask, but I would need all this information to make sure I advise you with the best solution to your problem and hopefully get your site up and running again...

**Comment by CaughtInTheBrambles** [comment]
Hi

1) Site was originally installed using composer and drupal/drupal
2) The original composer.json looked like this October 2017
`{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.24",
        "wikimedia/composer-merge-plugin": "^1.4",
        "drupal/webform": "^5.0@beta",
        "drupal/paragraphs": "^1.2",
        "drupal/bootstrap": "^3.6",
        "drupal/bootstrap_paragraphs": "^2.0@beta",
        "drupal/pathauto": "^1.0",
        "drupal/token": "^1.0",
        "drupal/admin_toolbar": "^1.20",
        "drupal/google_analytics": "^2.2",
        "drupal/ds": "^3.1",
        "drupal/honeypot": "^1.27",
        "drupal/cookieconsent": "^1.2",
        "drupal/libraries": "3.x-dev",
        "drupal/views_bootstrap": "^3.0",
        "drupal/config_split": "^1.2",
        "drupal/bootstrap_layouts": "^5.1",
        "drupal/geofield": "^1.0@alpha",
        "drupal/geocoder": "^2.0@alpha",
        "drupal/address": "^1.2",
        "drupal/metatag": "^1.3",
        "drupal/smtp": "^1.0@beta",
        "drupal/backup_migrate": "^4.0@beta",
        "drupal/file_browser": "^1.1",
        "drupal/rules": "^3.0",
        "drupal/core": "~8.6",
        "drupal/eva": "^1.2",
        "drupal/viewsreference": "^1.0",
        "drupal/image_widget_crop": "^2.1",
        "drupal/svg_formatter": "^1.5",
        "drupal/dropzonejs": "^2.0",
        "drupal/video_embed_field": "^2.0",
        "drupal/media_entity_actions": "^1.0",
        "drupal/search_api": "^1.6",
        "drupal/redirect": "^1.0",
        "drupal/inline_entity_form": "^1.0",
        "drupal/media_entity": "^1.7",
        "drupal/media_entity_twitter": "^1.3",
        "drupal/easy_install": "^10.0",
        "drupal/xmlsitemap": "^1.0",
        "drupal/leaflet": "^1.0",
        "drupal/leaflet_more_maps": "^1.0",
        "drupal/geysir": "^1.0",
        "drupal/views_geojson": "1.x-dev",
        "drupal/easy_breadcrumb": "^1.8",
        "drupal/eu_cookie_compliance": "^1.2",
        "webkings-ca/gocomposer": "dev-master",
        "drush/drush": "^9.5"
		
    },

    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        },
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": [
          "Drupal\\Core\\Composer\\Composer::ensureHtaccess"
        ],
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}`
3) Just after it loads the libraries. Sorry cannot provide a full log.
4) This is on Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-142-generic x86_64) running on a VM under Virtualbox on Windows 10 PHP is 7.0.33
5) and 6)
![image](https://user-images.githubusercontent.com/695184/53555510-fc163800-3b39-11e9-91fd-1320505e219d.png)

Theme is Bootstrap 3 

I hope that's enlightening

Tim

**Comment by WebKings-ca** [comment]
I would need the full log of when you run the plug-in to know if the issue is related to mis-configuration on your end or a bug in the plug-in...

Also, You have to use code tags when posting your output since the way you have posted your composer.json is not clear due to the reason above... It also seems weird that you indicate that the composer.json file you have posted you claim it's your version from October 2017, But it does have my plug-in as a dependency in your composer.json... On October 2017, this plug-in didn't exist, so if you could elaborate on this point that'll be helpful...

**Comment by CaughtInTheBrambles** [comment]
Sorry I clearly didn't check so just picked the earliest committed version of composer.json from the git repo. 

Will have another look.

The VM is closed down now. have lots of drupal related stuff to do for next three days (Sorting an issue and volunteering at Drupalcamp London) so the logs are unavailable for the moment.

**Comment by CaughtInTheBrambles** [comment]
<code>
{
    "name": "drupal/drupal",
    "description": "Drupal is an open source content management platform powering millions of websites and applications.",
    "type": "project",
    "license": "GPL-2.0+",
    "require": {
        "composer/installers": "^1.0.24",
        "wikimedia/composer-merge-plugin": "^1.4",
        "drupal/webform": "^5.0@beta",
        "drupal/paragraphs": "^1.2",
        "drupal/bootstrap": "^3.6",
        "drupal/bootstrap_paragraphs": "^2.0@beta",
        "drupal/pathauto": "^1.0",
        "drupal/token": "^1.0",
        "drupal/admin_toolbar": "^1.20",
        "drupal/google_analytics": "^2.2",
        "drupal/ds": "^3.1",
        "drupal/honeypot": "^1.27",
        "drupal/cookieconsent": "^1.2",
        "drupal/media": "1.x-dev",
        "drupal/libraries": "3.x-dev"
    },
    "replace": {
        "drupal/core": "^8.4"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "preferred-install": "dist",
        "autoloader-suffix": "Drupal8"
    },
    "extra": {
        "_readme": [
            "By default Drupal loads the autoloader from ./vendor/autoload.php.",
            "To change the autoloader you can edit ./autoload.php.",
            "This file specifies the packages.drupal.org repository.",
            "You can read more about this composer repository at:",
            "https://www.drupal.org/node/2718229"
        ],
        "merge-plugin": {
            "include": [
                "core/composer.json"
            ],
            "recurse": false,
            "replace": false,
            "merge-extra": false
        },
        "installer-paths": {
            "core": ["type:drupal-core"],
            "modules/contrib/{$name}": ["type:drupal-module"],
            "profiles/contrib/{$name}": ["type:drupal-profile"],
            "themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"],
            "modules/custom/{$name}": ["type:drupal-custom-module"],
            "themes/custom/{$name}": ["type:drupal-custom-theme"]
        }
    },
    "autoload": {
        "psr-4": {
            "Drupal\\Core\\Composer\\": "core/lib/Drupal/Core/Composer"
        }
    },
    "scripts": {
        "pre-autoload-dump": "Drupal\\Core\\Composer\\Composer::preAutoloadDump",
        "post-autoload-dump": [
          "Drupal\\Core\\Composer\\Composer::ensureHtaccess"
        ],
        "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
        "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ]
}
</code>
This should be the initial composer.json.

**Comment by WebKings-ca** [comment]
Marking this issue as Closed... I will not re-open until you provide the correct information and full output once you run the plug-in... Also, you not posting your code properly after being asked multiple times, makes it difficult to help your use case...

**Comment by jimrome** [comment]
You are wrong. https://github.com/drush-ops/drush/issues/4329#issuecomment-589189012
