### ISSUE TITLE
Exception: Unable to determine Drupal core version.

### ISSUE THREAD

**Issue by w-la** [WebKings-ca/gocomposer#5]
I run:
composer require webkings-ca/gocomposer:dev-master
    1/1:	https://packages.drupal.org/8/drupal/provider-2019-1$a1ccb8a6d36f07025963cb8a99390a0d4fca7ead7f3944dc16219f9a668bb6ba.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
    1/4:	http://repo.packagist.org/p/provider-latest$a4d8377673027f22713b7742c9322c233ce18d60c3a555ac4f02148616614209.json
    2/4:	http://repo.packagist.org/p/provider-2018-10$b00932145a84881538241002331421c1277b74f512e6376b3246cc9306d04146.json
    3/4:	http://repo.packagist.org/p/provider-2019-01$aa240b5d56bf939b26a146c50beea71ce2f6c1c6714e3924dcaa768a0301b9c2.json
    4/4:	http://repo.packagist.org/p/provider-2017$941ece9a5a4d858cc533f42ba957615605e4be8d7107a7aa3d71dc54e96f85a3.json
    Finished: success: 4, skipped: 0, failure: 0, total: 4
./composer.json has been updated
Gathering patches for root package.
No patches supplied.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 0 removals
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
composer require webkings-ca/gocomposer:dev-master
    1/2:	https://packages.drupal.org/8/drupal/provider-2017-2$901b018f6720a79fe3271db7f8d9f218d6286da6008c4f3e8ef1ca703aaf5f28.json
    2/2:	https://packages.drupal.org/8/drupal/provider-2019-1$58901cb942bb2b8e132305d32f08968f6aed2794174ec2e4337713e83ec0cb11.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
    1/3:	http://repo.packagist.org/p/provider-latest$ad07fcf5637da8668a4008ec77c710fb2a7b006714a07b82c682c159458c0564.json
    2/3:	http://repo.packagist.org/p/provider-2018-10$23d4bfa5e87ccebabc60580310356e391cb67b606b16dd274fb50097836ebdac.json
    3/3:	http://repo.packagist.org/p/provider-2019-01$a97f939bf3fda74657c5d7380541ca5f8a92e33b221340e29ee0ee25521cbc20.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
./composer.json has been updated
Gathering patches for root package.
No patches supplied.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
No patches supplied.
Gathering patches for dependencies. This might take a minute.
  - Installing webkings-ca/gocomposer (dev-master 9f02381): Cloning 9f02381431 from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess

composer gocomposer does a few questions and starts the backup.
Final result:
                                                                                                                       
[OK] Success: Your Site Files and Database have been backedup to the /backup folder..                                    [Exception]                               
  Unable to determine Drupal core version.  
gocomposer (in green)

nothing further has been changed.

From the old similar issue I've checked my library folder. I'm only using the superfish library.
The actually installed Drupal version is 8.6.10. The installation is locally only.
Any idea, what could be wrong?

**Comment by WebKings-ca** [comment]
Nothing in your post (especially the links) is related in any way, shape or form to the GoComposer Plugin.. And Judging from your User profile and activity, I highly believe your post has been done in bad faith... If you're really facing an issue with the "GoComposer" plugin, Please post the Exact output (formatted with code tags so that it's more readable) in a new issue queue.. Don't post "Links" that don't make sense like the ones in your initial post here...

Closing This Issue....
